services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    network_mode: host
    env_file:
      - ./.env
    environment:
      TZ: ${TZ:-Europe/Amsterdam}
    volumes:
      - ${HOME}/Services/data/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

  hass-proxy:
    image: alpine/socat
    container_name: hass_proxy
    restart: unless-stopped
    command: TCP-LISTEN:8123,fork TCP-CONNECT:host.docker.internal:8123
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ingress
    labels:
      traefik.enable: "true"
      traefik.http.routers.hass.entrypoints: websecure
      traefik.http.routers.hass.rule: Host(`${HOME_ASSISTANT_HOST}`)
      traefik.http.routers.hass.tls: "true"
      traefik.http.services.hass.loadbalancer.server.port: "8123"

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    privileged: true
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${HOME}/Services/data/matter-server:/data
      - /run/dbus:/run/dbus:ro

networks:
  ingress:
    name: proxy-network
    external: true
