#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_shadow float
yabai -m config split_ratio 0.50
yabai -m config auto_balance on
yabai -m config mouse_modifier fn

yabai -m config mouse_action2 resize
yabai -m config auto_padding on
yabai -m config auto_padding_min_aspect 2.33
yabai -m config auto_padding_width 1600
yabai -m config auto_padding_height 1400

# yabai -m config external_bar main:30:0

#yabai -m config window_animation_duration 0.0

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

#yabai -m config window_opacity on
#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity 1.0

# window rules
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off border=off
yabai -m rule --add app="^About This Mac$" manage=off
yabai -m rule --add app="^Home" manage=off
yabai -m rule --add app="^1Clipboard$" manage=off
yabai -m rule --add app="^Dock$" manage=off
yabai -m rule --add app="^Photos$" manage=off
yabai -m rule --add app="^Screen Studio$" manage=off
yabai -m rule --add app="^AirBuddy$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off layer=above
yabai -m rule --add app="^Übersicht$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^iStat Menus$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^NotchNook$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# Spaces -----------------

# Work Stuff - Space 1
yabai -m rule --add app="^Linear$" space=1 manage=on
yabai -m rule --add app="^Slack$" space=1 manage=on
yabai -m rule --add app="^WhatsApp$" space=1 manage=on

# Education - Space 1
yabai -m rule --add app="^Anki$" space=1 manage=on
yabai -m rule --add app="^Notability$" space=1 manage=on

# Web Browsing - Space 2
yabai -m rule --add app="^Firefox Developer Edition$" space=2 manage=on
yabai -m rule --add app="^Tor Browser$" space=2 manage=on
yabai -m rule --add app="^Safari$" space=2 manage=on
#yabai -m rule --add app="^Google Chrome$" space=2 manage=on

# Tasks & Events Dashboard - Space 3
yabai -m rule --add app="^Things$" space=3 manage=on
yabai -m rule --add app="^Calendar$" space=3 manage=on
yabai -m rule --add app="^Messages$" space=3 manage=on

# Coding - Space 4
yabai -m rule --add app="^Zed$" space=4 manage=on
yabai -m rule --add app="^Code$" space=4 manage=on

# Tools & Utilities - Space 5
yabai -m rule --add app="^KeePassXC$" space=5 manage=on
yabai -m rule --add app="^1Password$" space=5 manage=on
yabai -m rule --add app="^System Settings$" manage=off space=5
yabai -m rule --add app="^Proton VPN$" manage=off space=5

# Entertainment - Space 6
yabai -m rule --add app="^Music$" manage=off space=6

echo "yabai configuration loaded.."
