#!/usr/bin/env sh

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)"

cd "${REPO_ROOT}"

exec /usr/bin/sudo /nix/var/nix/profiles/default/bin/nix \
  --extra-experimental-features nix-command \
  --extra-experimental-features flakes \
  run github:LnL7/nix-darwin/6a771120d607dcccb279a27d227650e324815c35#darwin-rebuild -- \
  switch --flake .#gamma
